#!/bin/bash

if [[ -n "$1" ]]; then
    input="$1"
elif [[ ! -t 0 ]]; then
    input="/dev/stdin"
else
    echo "No input file provided"
    exit 1
fi

while IFS= read -r fqdn
do
    fqdn_ip=$(nslookup "$fqdn" | grep 'Address:' | grep -v '#' | tail -1 | awk '{print $NF}')
    echo "$fqdn $fqdn_ip"
done < "$input"


