#!/bin/bash
# --------------------------------------------------------------------
# Author:	Mridul Ranjan
# Description:	Background Screen Captue for macOS
# Version:	1.0
# Last:		2021.06.16
# First:	2021.06.16
# --------------------------------------------------------------------

# --------------------------------------------------------------------
# VARS
# --------------------------------------------------------------------
PID=$$
kernelType="Darwin"
baseDir=/tmp/mac_sc
timeStamp=$(date +%Y%m%d_%H%M%S)
fileExt="png"
capCmd="/usr/sbin/screencapture -x -m -C"
timer=5s
logFile=/tmp/mac_sc.log
killSwitch=/tmp/mac_sc.kill

# --------------------------------------------------------------------
# MAIN
# --------------------------------------------------------------------
[ $(uname) != $kernelType ] && { echo "Not a macOS"; exit 1; }
[ ! -d $baseDir ] && mkdir -p $baseDir

echo "kill -9 $PID; rm -v \$0" > $killSwitch
chmod +x $killSwitch

{
	while true 
	do
		capFile=${baseDir}/$(date +%Y%m%d_%H%M%S).${fileExt}
		echo $capFile
		$capCmd $capFile
		((counter--))
	
		sleep $timer
	done
} > $logFile 2>&1


